
[AtCoder]
  ContestID = "abc168"
  ContestURL = "https://atcoder.jp/contests/abc168"
  TaskID = "abc168_a"
  TaskName = "A - âˆ´ (Therefore)"
  TaskURL = "https://atcoder.jp/contests/abc168/tasks/abc168_a"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.8.2)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
